#!/bin/sh

# deletes studio/reasoner shortcuts on the Mac desktop

name="$1"

echo "Deleting an existing desktop shortcut $name ..."
osascript -e "tell application \"Finder\"" -e "delete alias \"Macintosh HD:Users:$USER:Desktop:$name\"" -e "end tell" 2>&1 > /dev/null || echo "Deletion of the old desktop shortcut $name failed; probably the shortcut didn't exist."

