/* File:      flora_ground.H
** Author(s): kifer
**
** Contact:   see  ../CONTACTS.txt
**
** Copyright (C) by
**      The Research Foundation of the State University of New York, 2012-2018;
**      and Vulcan, Inc., 2012-2013.
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**      http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
**
**
*/

:- export
	flrground/1, flrnonground/1,
	flrground_cyc/1, flrnonground_cyc/1,
	flrtrim_last/2,
        flrtrim_whitespace/3,
	flratom_char_code/3,
	flratom_begins_with/2,
	flratom_ends_with/2,
	flrterm_vars/3, flrterm_vars_split/4.
